name: Create Release Builds
on:
push:
tags:
- "v*" # matches v1.0.1, v1.2, v2, etc


jobs:
once:
name: Create GitHub release
runs-on: ubuntu-latest
outputs:
upload_url: ${{ steps.create_release.outputs.upload_url }}
steps:
- name: Create a release
id: create_release
uses: actions/create-release@v1
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
with:
tag_name: ${{ github.ref }}
release_name: Release ${{ github.ref }}
draft: true
prerelease: true


build:
name: Create cross-platform release build, tag and upload binaries
needs: once
runs-on: ${{ matrix.os }}
strategy:
matrix:
os: [ubuntu-latest, macos-latest, windows-latest]
steps:
- uses: actions/checkout@v1
with:
submodules: true


  - name: Install latest CMake
    uses: lukka/get-cmake@latest

  - name: Run CMake (generation and build)
    uses: lukka/run-cmake@v2
    with:
      cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
      cmakeBuildType: Release
      buildDirectory: "${{ github.workspace }}/${{ matrix.os }}"

  - name: Upload Release Asset
    id: upload-release-asset
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ needs.once.outputs.upload_url }}
      asset_path: ${{ github.workspace }}/${{ matrix.os }}/xtest
      asset_name: xtest-${{ matrix.os }}
      asset_content_type: application/octet-stream